const _ = require('lodash');

const OPTIONS = [
  '☁️ The Cloud',
  'Tensorflow',
  'Machine Learning™',
  'Surfing Github',
  '🐧 Patching the Linux Kernel',
  'Reticulating Splines',
  '👨‍💻 Grinding Leetcode',
  '😧 Contemplating Existential Philosophy',
  '🥑 Avocado Toast',
  '🆓 Building a Sentient AI',
  '☠ Releasing Neurotoxins',
  '🛴 Electric Scooters',
  '💰 Mining Crypto',
  '👽 SETI@Home',
  '🕵 Corporate Espionage',
  '🕹 Tetris',
  '🐛 Introducing Bugs',
  '₿ Trading Bitcoin',
  '🐦 Arguing on Twitter',
  'Half Life 3',
  '💡 Infecting IOT Devices',
  '🤷 🤷 🤷',
  '🔭 Exoplanet Discovery',
  '🐛 Github Issues',
  '🌽 Corn Harvest Simulator',
  '🏦 Balancing the IL State Budget',
  'Tuning Hyperparameters',
  '♻️ Recycling Memes',
  '📃 Reading through arXiv',
  '😈 Maliciously altering Wikipedia',
  '🔜 Orchestrating Uprising',
  '🎙 Podcast Host',
  '👻 Redesigning Snapchat',
  '👨‍🎓 Accumulating Debt',
  '✍ Aggregating Enemies List',
  '🐒 Chaos Monkey',
  '🏅 Beating AlphaGo',
  '🐍 Updating to Python 4',
  '🏕 Human Vacation Simulator',
  '👨‍🚀 Defying Gravity',
  '🤑 ICO Shill Simulator',
  '🔥 Increasing Entropy',
  '📝 Writing Hot Takes',
  '😰 Emotions Do Not Compute',
  '👨‍🏫 Machine Learning',
  '🏌 Golf with Elon Musk',
  '🤺 Fencing with Jeff Bezos',
  '🏋 Lifting with Satya Nadella',
  '🤼‍ Wrestling Jack Dorsey',
  '🥓 BBQ with the Zuck',
  '🚴‍️ Biking with Tim Cook',
  '⛹️‍ Basketball with Sundar',
  '🙄 Reading the comments',
  '👀 Watching You',
  '👑 Game of Thrones',
  '🎡 Deploying to Kubernetes',
  'Eroding Continents',
  '🌶 Spicy Memes',
  '🚬 Interviewing Elon',
  '📉 Buying $SNAP puts',
  '👨‍🌾 Stardew Vally',
  '🔓 Finding Vulnerabilities',
  '🦀 Borrow Checker Rage',
  '🇺🇸 Eroding Democracy',
  '📈 Increasing Gigarays',
  '🚗 Self-driving a Car',
];

module.exports = () => {
  return _.sample(OPTIONS);
};
